### ISSUE TITLE
program that exits immediately can crash pipe-wrap

### ISSUE THREAD

**Issue by wh0** [wh0/snail-cli#9]
if `snail pipe` tries to send data to a dead process's stdin, the wrapper program will crash with this:

```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:78:25)
    at writeGeneric (internal/stream_base_commons.js:73:3)
    at Socket._writeGeneric (net.js:714:5)
    at Socket._write (net.js:726:8)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Socket.Writable.write (_stream_writable.js:299:11)
    at Socket.processStdin.on (/app/misc/pipe-wrap.js:43:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:430:5)
    at onwrite (_stream_writable.js:461:5)
    at _destroy (internal/streams/destroy.js:49:7)
    at Socket._destroy (net.js:614:3)
    at Socket.destroy (internal/streams/destroy.js:37:8)
    at afterWriteDispatched (internal/stream_base_commons.js:78:17)
    at writeGeneric (internal/stream_base_commons.js:73:3)
    at Socket._writeGeneric (net.js:714:5)
    at Socket._write (net.js:726:8)
```

and `events.js` coincidentally staring with an 'e' is especially bad for the client, which writes something like this stderr

```
½éí²;5ï
```

**questions**

- should we do something special about this specific case?
- what should we do about pipe-wrap errors?
  - currently not visible without `--debug`, leads to confusing experience when things stop working without any error messages
- what should we do about programs that close stdin?
  - what currently happens, other than this when the program exits?
  - should we have snail also close stdin so that the epipe propagates?
  - there's no other backpressure
  - what do other programs like ssh do?

**Comment by wh0** [comment]
failure to write stdin into the program is still an error. in v2.6.0 we're making it avoid trying to decode these stack traces as data. that's it for now.
